services:
  - type: web
    name: resume-scorer
    env: python
    buildCommand: pip install -r resume_scorer/requirements.txt && python resume_scorer/manage.py collectstatic --noinput && python resume_scorer/manage.py migrate
    startCommand: gunicorn resume_scorer.wsgi:application
    workingDir: resume_scorer
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: resume_scorer.settings
      - key: GROQ_API_KEY
        sync: false
